
public enum ASCII: UInt8, Sendable {
    case null
    case soh
    case startOfText
    case endOfText
    case endOfTransmission
    case enquiry
    case acknowledge
    case bell
    case backspace
    case horizontalTab
    case lineFeed
    case verticalTabulation
    case formFeed
    case carriageReturn
    case shiftOut
    case shiftIn
    case dataLinkEscape
    case deviceControlOne
    case deviceControlTwo
    case deviceControlThree
    case deviceControlFour
    case negativeAcknowledge
    case synchronousIdle
    case endOfTransmissionBlock
    case cancel
    case endOfMedium
    case substitute
    case escape
    case fileSeparator
    case groupSeparator
    case recordSeparator
    case unitSeparator

    case space
    case exclamation
    case quotation
    case pound
    case dollar
    case percent
    case ampersand
    case apostrophe
    case openParenthesis
    case closeParenthesis
    case asterisk
    case plus
    case comma
    case minus
    case period
    case forwardSlash

    case zero
    case one
    case two
    case three
    case four
    case five
    case six
    case seven
    case eight
    case nine

    case colon
    case semicolon
    case lessThan
    case equals
    case greaterThan
    case questionMark
    case atSign

    case A
    case B
    case C
    case D
    case E
    case F
    case G
    case H
    case I
    case J
    case K
    case L
    case M
    case N
    case O
    case P
    case Q
    case R
    case S
    case T
    case U
    case V
    case W
    case X
    case Y
    case Z

    case openBracket
    case backslash
    case closeBracket
    case caret
    case underscore
    case graveAccent

    case a
    case b
    case c
    case d
    case e
    case f
    case g
    case h
    case i
    case j
    case k
    case l
    case m
    case n
    case o
    case p
    case q
    case r
    case s
    case t
    case u
    case v
    case w
    case x
    case y
    case z

    case openBrace
    case verticalBar
    case closeBrace
    case tilde
    case delete

    // MARK: TODO: add extended
}