
// https://wiki.osdev.org/PS/2_Keyboard#Scan_Code_Set_2
extension KeyboardScancodes.Qwerty {
    public static let ps2Set2: [_ of KeyEvent] = {
        var t = [132 of KeyEvent].init(initializingWith: {
            for i in 0..<132 {
                $0.append(.pressed(.unknown))
            }
        })
        t[0x01] = .pressed(.f9)
        t[0x03] = .pressed(.f5)
        t[0x04] = .pressed(.f3)
        t[0x05] = .pressed(.f1)
        t[0x06] = .pressed(.f2)
        t[0x07] = .pressed(.f12)
        t[0x09] = .pressed(.f10)
        t[0x0A] = .pressed(.f8)
        t[0x0B] = .pressed(.f6)
        t[0x0C] = .pressed(.f4)
        t[0x0D] = .pressed(.tab)
        t[0x0E] = .pressed(.backtick)
        t[0x11] = .pressed(.leftAlt)
        t[0x12] = .pressed(.leftShift)
        t[0x14] = .pressed(.leftCtrl)
        t[0x15] = .pressed(.q)
        t[0x16] = .pressed(.one)
        t[0x1A] = .pressed(.z)
        t[0x1B] = .pressed(.s)
        t[0x1C] = .pressed(.a)
        t[0x1D] = .pressed(.w)
        t[0x1E] = .pressed(.two)
        t[0x21] = .pressed(.c)
        t[0x22] = .pressed(.x)
        t[0x23] = .pressed(.d)
        t[0x24] = .pressed(.e)
        t[0x25] = .pressed(.four)
        t[0x26] = .pressed(.three)
        t[0x29] = .pressed(.space)
        t[0x2A] = .pressed(.v)
        t[0x2B] = .pressed(.f)
        t[0x2C] = .pressed(.t)
        t[0x2D] = .pressed(.r)
        t[0x2E] = .pressed(.five)
        t[0x31] = .pressed(.n)
        t[0x32] = .pressed(.b)
        t[0x33] = .pressed(.h)
        t[0x34] = .pressed(.g)
        t[0x35] = .pressed(.y)
        t[0x36] = .pressed(.six)
        t[0x3A] = .pressed(.m)
        t[0x3B] = .pressed(.j)
        t[0x3C] = .pressed(.u)
        t[0x3D] = .pressed(.seven)
        t[0x3E] = .pressed(.eight)
        t[0x41] = .pressed(.comma)
        t[0x42] = .pressed(.k)
        t[0x43] = .pressed(.i)
        t[0x44] = .pressed(.o)
        t[0x45] = .pressed(.zero)
        t[0x46] = .pressed(.nine)
        t[0x49] = .pressed(.period)
        t[0x4A] = .pressed(.slash)
        t[0x4B] = .pressed(.l)
        t[0x4C] = .pressed(.semicolon)
        t[0x4D] = .pressed(.p)
        t[0x4E] = .pressed(.minus)
        t[0x52] = .pressed(.apostrophe)
        t[0x54] = .pressed(.leftBracket)
        t[0x55] = .pressed(.equal)
        t[0x58] = .pressed(.capsLock)
        t[0x59] = .pressed(.rightShift)
        t[0x5A] = .pressed(.enter)
        t[0x5B] = .pressed(.rightBracket)
        t[0x5D] = .pressed(.backslash)
        t[0x66] = .pressed(.backspace)
        t[0x69] = .pressed(.keypadOne)
        t[0x6B] = .pressed(.keypadFour)
        t[0x6C] = .pressed(.keypadSeven)
        t[0x70] = .pressed(.keypadZero)
        t[0x71] = .pressed(.keypadPeriod)
        t[0x72] = .pressed(.keypadTwo)
        t[0x73] = .pressed(.keypadFive)
        t[0x74] = .pressed(.keypadSix)
        t[0x75] = .pressed(.keypadEight)
        t[0x76] = .pressed(.escape)
        t[0x77] = .pressed(.numberLock)
        t[0x78] = .pressed(.f11)
        t[0x79] = .pressed(.keypadPlus)
        t[0x7A] = .pressed(.keypadThree)
        t[0x7B] = .pressed(.keypadMinus)
        t[0x7C] = .pressed(.keypadAsterisk)
        t[0x7D] = .pressed(.keypadNine)
        t[0x7E] = .pressed(.scrollLock)
        t[0x83] = .pressed(.f7)
        return t
    }()
}